name: Simple Reusable Workflow
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Test Step
        run: echo "Testing workflow access"