# .github/workflows/simple-workflow.yml
name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Say Hello
        run: echo "Hello from the workflows repo!"