# .github/workflows/simple-workflow.yml
name: Simple Workflow

on:
  workflow_call:
    inputs:
      message:
        description: 'Message to display'
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display message
        run: echo "${{ inputs.message }}"
